### PR TITLE
Fix location of stack trace

### LINKED ISSUE #198: Print stack trace before instruction executes
Per @cdetrio:

> stack pointer starting at -32 https://github.com/ewasm/evm2wasm/blob/master/index.js#L509

> this whole thing needs to be moved up, because the trace should print before the instruction executes (standardized trace). where it is now, it prints after the first instruction https://github.com/ewasm/evm2wasm/blob/master/index.js#L319-L322

Cf. https://github.com/ewasm/hera/issues/164

### PR DESCRIPTION
**Pull request by lrettig**
Print the stack trace before the operation rather than after.

Closes #198.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -187,6 +187,11 @@ exports.evm2wast = function (evmCode, opts = {
       segmentStackLow = segmentStackDeta
     }
 
+    // creates a stack trace
+    if (opts.stackTrace) {
+      segment += `(call $stackTrace (i32.const ${pc}) (i32.const ${opint}) (i32.const ${gasCount}) (get_global $sp))\n`
```
Comment (axic) [inline index.js]: I think the stack pointer will be broken if it is done before? Needs to be fixed however.

Comment (lrettig) [reply index.js]: I'm pretty sure it's correct. I looked into this earlier on the call with Casey, and also mentioned it in the commitlog. Here's the trace output as is, which looks correct:

```
Executing...
importGlobals
useGas 12
evmTrace
{"depth":0,"gas":378988,"gasCost":3,"op":96,"pc":0,"stack":[]}
evmTrace
{"depth":0,"gas":378988,"gasCost":6,"op":96,"pc":2,"stack":["0x0000000000000000000000000000000000000000000000000000000000000001"]}
evmTrace
{"depth":0,"gas":378988,"gasCost":9,"op":1,"pc":4,"stack":["0x0000000000000000000000000000000000000000000000000000000000000001","0x0000000000000000000000000000000000000000000000000000000000000001"]}
evmTrace
{"depth":0,"gas":378988,"gasCost":12,"op":96,"pc":5,"stack":["0x0000000000000000000000000000000000000000000000000000000000000002"]}
evmTrace
{"depth":0,"gas":378988,"gasCost":12,"op":85,"pc":7,"stack":["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000002"]}
storageStore 20 0
```

If I initialize `$sp` at zero rather than at -32, it adds an extra 0x00 onto the front of the stack in all cases, which seems wrong.

Comment (axic) [reply index.js]: Oh right, the client just ignores anything `<0`. Perhaps worth documenting that in the `evmTrace` "documentation".

Comment (lrettig) [reply index.js]: > Oh right, the client just ignores anything <0

I think I'm making the case that, by the time the first `stackTrace` runs, it _is_ zero.

> Perhaps worth documenting that in the evmTrace "documentation".

Do you mean a comment in this code?

Comment (axic) [reply index.js]: I think it is the README of Hera which has it at the moment.

**Comment by jwasinger** [comment]
Anything blocking the merge of this @axic @lrettig ? Ran it and compared to cpp-ethereum EVM `--jsontrace` output for `stExample/add11`.  LGTM

**Comment by axic** [comment]
@jwasinger adding the readme change to Hera or at least creating an issue in the Hera repo.

**Comment by lrettig** [comment]
Nope, just that per @axic the Hera README should also be updated. I haven't done this because I don't understand what @axic means by this:

> the client just ignores anything <0

Do you mean a negative `$sp` is set to zero or something?

**Comment by axic** [comment]
The stack dump loop IIRC ignores any `sp < 0`, so it is "valid" to call `evmTrace` with a negative `sp`.

**Comment by jwasinger** [comment]
> @jwasinger adding the readme change to Hera or at least creating an issue in the Hera repo.

Noted: https://github.com/ewasm/hera/pull/166

**Comment by jwasinger** [comment]
LGTM.  can we get this merged?

**Comment by lrettig** [comment]
Needs @axic's approval to merge

**Comment by axic** [comment]
@cdetrio can you review this?

**Comment by axic** [comment]
Here was @cdetrio's version from February but he never made a PR: https://github.com/ewasm/evm2wasm/commit/4753b8bd9525b6bed88b0782c6640cff520ac5c1
